### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/PerWorldPlugins#10]
[12:17:27] [Server thread/WARN]: java.lang.NullPointerException
[12:17:27] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor366.invoke(Unknown Source)
[12:17:27] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:17:27] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:17:27] [Server thread/WARN]: 	at JetPack.ItemStackUtils.getNBTString(ItemStackUtils.java:64)
[12:17:27] [Server thread/WARN]: 	at JetPack.JetPackHandler.clickJetPack(JetPackHandler.java:222)
[12:17:27] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor365.invoke(Unknown Source)
[12:17:27] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:17:27] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:17:27] [Server thread/WARN]: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120)
[12:17:27] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:17:27] [Server thread/WARN]: 	at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30)
[12:17:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[12:17:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[12:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1459)
[12:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:43)
[12:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:9)
[12:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[12:17:27] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:17:27] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[12:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[12:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[12:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[12:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[12:17:27] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[12:17:28] [Server thread/WARN]: java.lang.NullPointerException
[12:17:28] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor366.invoke(Unknown Source)
[12:17:28] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:17:28] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:17:28] [Server thread/WARN]: 	at JetPack.ItemStackUtils.getNBTString(ItemStackUtils.java:64)
[12:17:28] [Server thread/WARN]: 	at JetPack.JetPackHandler.clickJetPack(JetPackHandler.java:222)
[12:17:28] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor365.invoke(Unknown Source)
[12:17:28] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:17:28] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:17:28] [Server thread/WARN]: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120)
[12:17:28] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:17:28] [Server thread/WARN]: 	at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30)
[12:17:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[12:17:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1459)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:43)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:9)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[12:17:28] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:17:28] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[12:17:28] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[12:17:28] [Server thread/WARN]: java.lang.NullPointerException
[12:17:28] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor366.invoke(Unknown Source)
[12:17:28] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:17:28] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:17:28] [Server thread/WARN]: 	at JetPack.ItemStackUtils.getNBTString(ItemStackUtils.java:64)
[12:17:28] [Server thread/WARN]: 	at JetPack.JetPackHandler.clickJetPack(JetPackHandler.java:222)
[12:17:28] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor365.invoke(Unknown Source)
[12:17:28] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:17:28] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:17:28] [Server thread/WARN]: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120)
[12:17:28] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:17:28] [Server thread/WARN]: 	at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30)
[12:17:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[12:17:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1459)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:43)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:9)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[12:17:28] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:17:28] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[12:17:28] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[12:17:28] [Server thread/WARN]: java.lang.NullPointerException
[12:17:28] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor366.invoke(Unknown Source)
[12:17:28] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:17:28] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:17:28] [Server thread/WARN]: 	at JetPack.ItemStackUtils.getNBTString(ItemStackUtils.java:64)
[12:17:28] [Server thread/WARN]: 	at JetPack.JetPackHandler.clickJetPack(JetPackHandler.java:222)
[12:17:28] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor365.invoke(Unknown Source)
[12:17:28] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:17:28] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:17:28] [Server thread/WARN]: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120)
[12:17:28] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:17:28] [Server thread/WARN]: 	at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30)
[12:17:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[12:17:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1459)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:43)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:9)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[12:17:28] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:17:28] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[12:17:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[12:17:28] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[12:17:29] [Server thread/WARN]: java.lang.NullPointerException
[12:17:29] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor366.invoke(Unknown Source)
[12:17:29] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:17:29] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:17:29] [Server thread/WARN]: 	at JetPack.ItemStackUtils.getNBTString(ItemStackUtils.java:64)
[12:17:29] [Server thread/WARN]: 	at JetPack.JetPackHandler.clickJetPack(JetPackHandler.java:222)
[12:17:29] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor365.invoke(Unknown Source)
[12:17:29] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:17:29] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:17:29] [Server thread/WARN]: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120)
[12:17:29] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:17:29] [Server thread/WARN]: 	at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30)
[12:17:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[12:17:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1459)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:43)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:9)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[12:17:29] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:17:29] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[12:17:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[12:17:29] [Server thread/WARN]: java.lang.NullPointerException
[12:17:29] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor366.invoke(Unknown Source)
[12:17:29] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:17:29] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:17:29] [Server thread/WARN]: 	at JetPack.ItemStackUtils.getNBTString(ItemStackUtils.java:64)
[12:17:29] [Server thread/WARN]: 	at JetPack.JetPackHandler.clickJetPack(JetPackHandler.java:222)
[12:17:29] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor365.invoke(Unknown Source)
[12:17:29] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:17:29] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:17:29] [Server thread/WARN]: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120)
[12:17:29] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:17:29] [Server thread/WARN]: 	at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30)
[12:17:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[12:17:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1459)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:43)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:9)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[12:17:29] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:17:29] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[12:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[12:17:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by FormallyMyles** [comment]
PerWorldPlugins is officially discontinued, in addition, this error isn't related to PWP. "JetPack.ItemStackUtils.getNBTString"
