### ISSUE TITLE
Error in 1.14.4 loading

### ISSUE THREAD

**Issue by Hugman76** [MylesIsCool/PerWorldPlugins#16]
```
[18:23:37] [Server thread/INFO]: [PerWorldPlugins] Enabled, attempting to inject CommandHandler...
[18:23:37] [Server thread/ERROR]: PerWorldPlugins failed replacing the existing PluginLoader, contact the developers on BukkitDev!
java.lang.IllegalArgumentException: Can not set final org.bukkit.craftbukkit.v1_14_R1.command.CraftCommandMap field org.bukkit.craftbukkit.v1_14_R1.CraftServer.commandMap to me.incomprehendable.dev.pwp.FakeSimpleCommandMap
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Field.set(Unknown Source) ~[?:1.8.0_221]
	at me.incomprehendable.dev.pwp.PerWorldPlugins.onEnable(PerWorldPlugins.java:123) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [craftbukkit.jar:git-Bukkit-31adfa7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:344) [craftbukkit.jar:git-Bukkit-31adfa7]
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:141) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [craftbukkit.jar:git-Bukkit-31adfa7]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:447) [craftbukkit.jar:git-Bukkit-31adfa7]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:373) [craftbukkit.jar:git-Bukkit-31adfa7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [craftbukkit.jar:git-Bukkit-31adfa7]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:243) [craftbukkit.jar:git-Bukkit-31adfa7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:752) [craftbukkit.jar:git-Bukkit-31adfa7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

**Comment by TonimatasMCDEV** [comment]
This is doesn't important error. It happened to me but the plugin works correctly the same as /pwp reload
